SELECT 
    A.ACCOUNT_NUMBER,
    C.DESCRIPTION,
    B.DATE_OF_BIRTH,
    B.PLACE_OF_BIRTH,
    B.BIRTH_INCORP_DATE,
    B.PLACE_OF_INCORP,
    B.NATIONALITY,
    B.PHONE_1,
    B.SMS_1
FROM V_FBNK_CUSTOMER AS B
INNER JOIN V_FH01_CUSTOMER_ACCOUNT AS A ON B.RECID = A.RECID
INNER JOIN V_FBNK_SECTOR AS C ON C.RECID = B.SECTOR
WHERE A.ACCOUNT_NUMBER = '{0}';