SELECT 
    RECID AS UID, 
    MESSAGE_KEY, 
    TRANS_REFERENCE, 
    DATE_TIME_RECD AS DATE_TIME_RECEIVED, 
    DATE_TIME_PROC AS DATE_TIME_PROCESS, 
    STATUS, 
    MSG_IN, 
    MSG_OUT
FROM V_F_OFS_REQUEST_DETAIL 
WHERE RECID = '{0}'